version: '3'
services:
  serv:
    image: mlposey/pong-server
    restart: always
    ports:
      - 8001:8001

  web:
    image: nginx:1.13.6
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_PORT=80    
      - VIRTUAL_HOST=pong.marcusposey.com
    networks:
      - reverse-proxy
    depends_on:
      - serv
    volumes:
      - ./client:/usr/share/nginx/html:ro
networks:
  reverse-proxy:
    external:
      name: reverse-proxy